name = "ReviseResumable"
uuid = "80d58ff9-3b30-45f0-9ea0-2f24891a39e4"
authors = ["hdavid16 <hperez16@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
SimJulia = "428bdadb-6287-5aa5-874b-9969638295fd"

[compat]
ResumableFunctions = "0.5"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
